<?php

namespace App\Helpers;

class CustomHelper
{
    public static function sendNotification($fcm, $total)
    {
        $url = 'https://fcm.googleapis.com/fcm/send';
        $mydata = [
            'registration_ids' => $fcm,

            "data" => ["type" => 'Bills'],
            "android" => [
                "priority" => "high",
                "ttl" => 60 * 60 * 1,
                "android_channel_id" => "high_importance_channel"

            ],
            "notification" => [
                'title' => 'Monthly Bill', 'body' => 'A New Bill Is Generated By Finace Deparment is Rs ' . $total,

            ]

        ];
        $finaldata = json_encode($mydata);
        $headers = array(
            'Authorization: key=' . Config('app.serverkey'),
            'Content-Type: application/json'
        );
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_POST, true);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $finaldata);
        $result = curl_exec($ch);
        // var_dump($result);
        curl_close($ch);
    }
    
    // Add more helper functions as needed
}